# Project Title

Mobile Phone Dataset

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# Domain
Retail/ Mobile Phone Market Analysis

# Objective

1.Analyze mobile phone specifications and understand their impact on pricing.

2.Identify the relationship between features such as RAM, storage, battery capacity, and camera quality with the overall price.

3.Compare different brands based on performance, pricing, and customer ratings.

4.To examine how technical specifications influence customer satisfaction levels.

5.Identify pricing patterns across budget, mid-range, and premium segments.

6.Detect trends in smartphone features and market demand.

7.Generate meaningful insights using statistical and visualization techniques.

8.support data-driven decisions for product development and pricing strategies.

9.Recommend optimal feature combinations that provide better market competitiveness.

# Outcome

The outcome of this project is the identification of key mobile phone features such as RAM, storage, battery capacity, camera quality, and processor that significantly influence pricing and customer ratings. The analysis highlights brand-wise comparisons, market positioning, and pricing patterns across different segments. It provides meaningful insights into how technical specifications impact customer satisfaction and overall product value. These findings support data-driven decisions for product development, competitive pricing strategies, and improved market performance.

#Dataset Information

Source: Kaggle

Year / Timeline: Data collected during 2025

Dataset Description:The dataset contains detailed information about various mobile phones, including brand name, model, price, technical specifications (such as RAM, storage, battery capacity, camera, processor, and display size), operating system, and customer ratings. It is designed to analyze how different features influence pricing, performance, and customer satisfaction in the smartphone market.

Name - Mobile Phone Dataset

# Type of Analysis

Descriptive Analysis-Summarizes the basic features of the dataset such as average price, most common RAM and storage, brand distribution, and overall rating trends.

Diagnostic Analysis-Examines relationships between variables to understand why certain phones are priced higher, such as the impact of RAM, battery, and camera on price.

Predictive Analysis-Uses statistical models (like regression) to predict mobile phone price or rating based on features such as RAM, storage, and processor.

Prescriptive Analysis-Provides recommendations for optimal feature combinations and pricing strategies to improve competitiveness and customer satisfaction.

# Stages for DA Project

## Stage 1 – Problem Definition and Dataset Selection

Problem Definition:The smartphone market offers a wide range of mobile phones with varying specifications, brands, and price levels, making it difficult to understand how different features influence pricing and customer satisfaction. Consumers often struggle to determine whether a phone's price accurately reflects its technical specifications, while businesses need data-driven insights to design competitive products and set optimal pricing strategies. Therefore, this project aims to analyze mobile phone data to identify the relationship between features, price, and customer ratings, and to uncover meaningful patterns that support better decision-making in the smartphone market.

Expected Outcome:The expected outcome of this project is to identify the key factors that significantly influence mobile phone pricing and customer ratings. The analysis will reveal how features such as RAM, storage, battery capacity, camera quality, and processor affect overall product value. It will also highlight brand-wise performance comparisons and pricing trends across different market segments. The final outcome will provide meaningful insights that support better business decisions, improved pricing strategies, and enhanced product development planning.


Dataset Selection Name: Mobile Phone Dataset

Source: Kaggle

Size: 500+ user records

Features: Brand, Model, Price, RAM Capacity, Internal Storage, Processor Type, Operating System, Camera Specifications, Battery Capacity, Display Size, and Customer Rating.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/ASSIGNMENT/Final project/Mobile Data.csv'
df = pd.read_csv(file_path)
df

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,Name,Company,Price,Star_Rating,Number_of_Ratings,Number_of_Reviews,Processor,Warranty,RAM_GB,ROM_GB,Expandable_GB
0,"Google Pixel 10 Pro Fold (Moonstone, 256 GB)",Google,172999,NaN,NaN,NaN,Tensor G5 Processor,1.0,16.0,256.0,NaN
1,"Samsung Galaxy F36 5G (Red, 128 GB)",Samsung,15999,4.3,7526.0,439.0,Samsung Exynos 1380 Processor,1.0,6.0,128.0,2048.0
2,"POCO C71 (Cool Blue, 128 GB)",POCO,6799,4.1,24904.0,1190.0,Unisoc T7250\nMax clock speed: \n2 x A75@1.8GH...,1.0,6.0,128.0,2048.0
3,"POCO M7 5G (Mint Green, 128 GB)",POCO,9999,4.2,12684.0,624.0,4 Gen 2 5G Processor,1.0,8.0,128.0,1024.0
4,"Samsung Galaxy F36 5G (Black, 256 GB)",Samsung,19499,4.2,3752.0,267.0,Samsung Exynos 1380 Processor,1.0,8.0,256.0,2048.0
...,...,...,...,...,...,...,...,...,...,...,...
979,"OPPO A5 5G (Mist White, 128 GB)",OPPO,15499,4.3,254.0,9.0,Dimensity 6300 Processor,1.0,6.0,128.0,NaN
980,"Samsung Galaxy F36 5G (Red, 256 GB)",Samsung,19499,4.2,3752.0,267.0,Samsung Exynos 1380 Processor,1.0,8.0,256.0,2048.0
981,"Google Pixel 9A (Iris, 256 GB)",Google,44999,4.4,3876.0,279.0,Tensor G4 Processor,1.0,8.0,256.0,NaN
982,GFive U550,GFive,899,3.7,158.0,11.0,NaN,NaN,NaN,NaN,NaN
983,"Ai+ Nova 5G (Green, 128 GB)",Ai+,9999,3.8,2742.0,244.0,T8200 Processor,1.0,8.0,128.0,1024.0

In [ ]:
#First Five rows
df.head()

,Name,Company,Price,Star_Rating,Number_of_Ratings,Number_of_Reviews,Processor,Warranty,RAM_GB,ROM_GB,Expandable_GB
0,"Google Pixel 10 Pro Fold (Moonstone, 256 GB)",Google,172999,NaN,NaN,NaN,Tensor G5 Processor,1.0,16.0,256.0,NaN
1,"Samsung Galaxy F36 5G (Red, 128 GB)",Samsung,15999,4.3,7526.0,439.0,Samsung Exynos 1380 Processor,1.0,6.0,128.0,2048.0
2,"POCO C71 (Cool Blue, 128 GB)",POCO,6799,4.1,24904.0,1190.0,Unisoc T7250\nMax clock speed: \n2 x A75@1.8GH...,1.0,6.0,128.0,2048.0
3,"POCO M7 5G (Mint Green, 128 GB)",POCO,9999,4.2,12684.0,624.0,4 Gen 2 5G Processor,1.0,8.0,128.0,1024.0
4,"Samsung Galaxy F36 5G (Black, 256 GB)",Samsung,19499,4.2,3752.0,267.0,Samsung Exynos 1380 Processor,1.0,8.0,256.0,2048.0

In [ ]:
# Last five Rows
df.tail()

,Name,Company,Price,Star_Rating,Number_of_Ratings,Number_of_Reviews,Processor,Warranty,RAM_GB,ROM_GB,Expandable_GB
979,"OPPO A5 5G (Mist White, 128 GB)",OPPO,15499,4.3,254.0,9.0,Dimensity 6300 Processor,1.0,6.0,128.0,NaN
980,"Samsung Galaxy F36 5G (Red, 256 GB)",Samsung,19499,4.2,3752.0,267.0,Samsung Exynos 1380 Processor,1.0,8.0,256.0,2048.0
981,"Google Pixel 9A (Iris, 256 GB)",Google,44999,4.4,3876.0,279.0,Tensor G4 Processor,1.0,8.0,256.0,NaN
982,GFive U550,GFive,899,3.7,158.0,11.0,NaN,NaN,NaN,NaN,NaN
983,"Ai+ Nova 5G (Green, 128 GB)",Ai+,9999,3.8,2742.0,244.0,T8200 Processor,1.0,8.0,128.0,1024.0

In [ ]:
#statistical summary
df.describe()

,Price,Star_Rating,Number_of_Ratings,Number_of_Reviews,Warranty,RAM_GB,ROM_GB,Expandable_GB
count,984.000000,942.000000,942.000000,942.000000,934.000000,839.000000,855.000000,436.000000
mean,27266.412602,4.262527,16596.082803,1002.267516,1.003212,63.543504,176.548538,1411.229358
std,36050.070240,0.218456,41382.796155,3916.120798,0.056614,1618.042173,85.814514,764.167829
min,499.000000,3.000000,4.000000,0.000000,1.000000,2.000000,0.000000,8.000000
25%,9999.000000,4.200000,2134.250000,135.000000,1.000000,6.000000,128.000000,1024.000000
50%,16999.000000,4.300000,3876.000000,279.000000,1.000000,8.000000,128.000000,2048.000000
75%,29999.000000,4.400000,11542.000000,741.500000,1.000000,8.000000,256.000000,2048.000000
max,172999.000000,4.800000,639594.000000,108978.000000,2.000000,46875.000000,512.000000,2048.000000

In [ ]:
# Check Data Types and Non-Null Counts
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 984 entries, 0 to 983
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               984 non-null    object
 1   Company            984 non-null    object
 2   Price              984 non-null    int64
 3   Star_Rating        942 non-null    float64
 4   Number_of_Ratings  942 non-null    float64
 5   Number_of_Reviews  942 non-null    float64
 6   Processor          813 non-null    object
 7   Warranty           934 non-null    float64
 8   RAM_GB             839 non-null    float64
 9   ROM_GB             855 non-null    float64
 10  Expandable_GB      436 non-null    float64
dtypes: float64(7), int64(1), object(3)
memory usage: 84.7+ KB

In [ ]:
# Check Shape
print("Dataset(Rows,Coloums)):", df.shape)

Dataset(Rows,Coloums)): (984, 11)

In [ ]:
#Datatypes of dataset
print("\nData Types:\n", df.dtypes)

Data Types:
 Name                  object
Company               object
Price                  int64
Star_Rating          float64
Number_of_Ratings    float64
Number_of_Reviews    float64
Processor             object
Warranty             float64
RAM_GB               float64
ROM_GB               float64
Expandable_GB        float64
dtype: object

In [ ]:
#  Check Null Value
print("-Null Values-")
df.isnull()

-Null Values-

,Name,Company,Price,Star_Rating,Number_of_Ratings,Number_of_Reviews,Processor,Warranty,RAM_GB,ROM_GB,Expandable_GB
0,False,False,False,True,True,True,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
979,False,False,False,False,False,False,False,False,False,False,True
980,False,False,False,False,False,False,False,False,False,False,False
981,False,False,False,False,False,False,False,False,False,False,True
982,False,False,False,False,False,False,True,True,True,True,True
983,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
#Total elements in dataset
print("Count of elements:", df.size)

Count of elements: 10824

In [ ]:
#Index values
print("Index value:",df.index)

Index value: RangeIndex(start=0, stop=984, step=1)

In [ ]:
#Columns
print("columns of Dataframe:",df.columns)

columns of Dataframe: Index(['Name', 'Company', 'Price', 'Star_Rating', 'Number_of_Ratings',
       'Number_of_Reviews', 'Processor', 'Warranty', 'RAM_GB', 'ROM_GB',
       'Expandable_GB'],
      dtype='object')

In [ ]:
#Null Values
print (f" Checking Null values : ")

df.isnull().sum()

 Checking Null values :

Name                   0
Company                0
Price                  0
Star_Rating           42
Number_of_Ratings     42
Number_of_Reviews     42
Processor            171
Warranty              50
RAM_GB               145
ROM_GB               129
Expandable_GB        548
dtype: int64

In [ ]:
# No of unique values
print(f" Number of Unique Values : ")
df.nunique()

 Number of Unique Values :

Name                 533
Company               42
Price                316
Star_Rating           18
Number_of_Ratings    305
Number_of_Reviews    234
Processor            118
Warranty               2
RAM_GB                 8
ROM_GB                 9
Expandable_GB         10
dtype: int64

In [ ]:
#Duplicate
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
979    False
980     True
981     True
982    False
983    False
Length: 984, dtype: bool

In [ ]:
# Duplicate Check
df.duplicated().sum()

np.int64(339)

## Stage 2 – Data Cleaning and Pre-processing

Handle missing values (impute or drop)

Handle duplicates

Treat outliers if required

Check skewness and apply transformations

Convert data types if needed

Feature transformations (date parts, derived fields if required for analysis)

In [ ]:
###Check Missing Values

df.isnull().sum()

Name                   0
Company                0
Price                  0
Star_Rating           42
Number_of_Ratings     42
Number_of_Reviews     42
Processor            171
Warranty              50
RAM_GB               145
ROM_GB               129
Expandable_GB        548
dtype: int64

In [ ]:
##Handle missing values (impute or drop)
##Numeric Columns

num_cols = df.select_dtypes(include=['int64','float64']).columns
for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

In [ ]:
##Categorical Columns
cat_cols = df.select_dtypes(include=['object']).columns

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [ ]:
df.isnull().sum()

Name                 0
Company              0
Price                0
Star_Rating          0
Number_of_Ratings    0
Number_of_Reviews    0
Processor            0
Warranty             0
RAM_GB               0
ROM_GB               0
Expandable_GB        0
dtype: int64

In [ ]:
##Handle duplicates

df.duplicated().sum()

np.int64(339)

In [ ]:
df.drop_duplicates(inplace=True)
df

,Name,Company,Price,Star_Rating,Number_of_Ratings,Number_of_Reviews,Processor,Warranty,RAM_GB,ROM_GB,Expandable_GB
0,"Google Pixel 10 Pro Fold (Moonstone, 256 GB)",Google,172999,4.3,3876.0,279.0,Tensor G5 Processor,1.0,16.0,256.0,2048.0
1,"Samsung Galaxy F36 5G (Red, 128 GB)",Samsung,15999,4.3,7526.0,439.0,Samsung Exynos 1380 Processor,1.0,6.0,128.0,2048.0
2,"POCO C71 (Cool Blue, 128 GB)",POCO,6799,4.1,24904.0,1190.0,Unisoc T7250\nMax clock speed: \n2 x A75@1.8GH...,1.0,6.0,128.0,2048.0
3,"POCO M7 5G (Mint Green, 128 GB)",POCO,9999,4.2,12684.0,624.0,4 Gen 2 5G Processor,1.0,8.0,128.0,1024.0
4,"Samsung Galaxy F36 5G (Black, 256 GB)",Samsung,19499,4.2,3752.0,267.0,Samsung Exynos 1380 Processor,1.0,8.0,256.0,2048.0
...,...,...,...,...,...,...,...,...,...,...,...
975,"Tecno Spark Go 1 (Startrail Black, 64 GB)",Tecno,6899,4.3,1725.0,82.0,Unisoc T61 Processor,1.0,3.0,64.0,1024.0
978,"OPPO F31 Pro+ 5G (Gemstone Blue, 256 GB)",OPPO,32999,4.4,187.0,22.0,7 Gen 3 Mobile Platform Processor,1.0,8.0,256.0,2048.0
979,"OPPO A5 5G (Mist White, 128 GB)",OPPO,15499,4.3,254.0,9.0,Dimensity 6300 Processor,1.0,6.0,128.0,2048.0
982,GFive U550,GFive,899,3.7,158.0,11.0,Samsung Exynos 1380 Processor,1.0,8.0,128.0,2048.0
983,"Ai+ Nova 5G (Green, 128 GB)",Ai+,9999,3.8,2742.0,244.0,T8200 Processor,1.0,8.0,128.0,1024.0

In [ ]:
# Check Skewness & Apply Transformation
df.skew(numeric_only=True)

Price                 3.309860
Star_Rating          -1.200244
Number_of_Ratings     5.882736
Number_of_Reviews    19.100715
Warranty             14.594343
RAM_GB               25.396784
ROM_GB                1.505566
Expandable_GB        -1.563887
dtype: float64

In [ ]:
# If skewed → Apply log transformation

df['Number_of_Ratings'] = np.log1p(df['Number_of_Ratings'])
df

,Name,Company,Price,Star_Rating,Number_of_Ratings,Number_of_Reviews,Processor,Warranty,RAM_GB,ROM_GB,Expandable_GB
0,"Google Pixel 10 Pro Fold (Moonstone, 256 GB)",Google,172999,4.3,8.262817,279.0,Tensor G5 Processor,1.0,16.0,256.0,2048.0
1,"Samsung Galaxy F36 5G (Red, 128 GB)",Samsung,15999,4.3,8.926252,439.0,Samsung Exynos 1380 Processor,1.0,6.0,128.0,2048.0
2,"POCO C71 (Cool Blue, 128 GB)",POCO,6799,4.1,10.122824,1190.0,Unisoc T7250\nMax clock speed: \n2 x A75@1.8GH...,1.0,6.0,128.0,2048.0
3,"POCO M7 5G (Mint Green, 128 GB)",POCO,9999,4.2,9.448175,624.0,4 Gen 2 5G Processor,1.0,8.0,128.0,1024.0
4,"Samsung Galaxy F36 5G (Black, 256 GB)",Samsung,19499,4.2,8.230311,267.0,Samsung Exynos 1380 Processor,1.0,8.0,256.0,2048.0
...,...,...,...,...,...,...,...,...,...,...,...
975,"Tecno Spark Go 1 (Startrail Black, 64 GB)",Tecno,6899,4.3,7.453562,82.0,Unisoc T61 Processor,1.0,3.0,64.0,1024.0
978,"OPPO F31 Pro+ 5G (Gemstone Blue, 256 GB)",OPPO,32999,4.4,5.236442,22.0,7 Gen 3 Mobile Platform Processor,1.0,8.0,256.0,2048.0
979,"OPPO A5 5G (Mist White, 128 GB)",OPPO,15499,4.3,5.541264,9.0,Dimensity 6300 Processor,1.0,6.0,128.0,2048.0
982,GFive U550,GFive,899,3.7,5.068904,11.0,Samsung Exynos 1380 Processor,1.0,8.0,128.0,2048.0
983,"Ai+ Nova 5G (Green, 128 GB)",Ai+,9999,3.8,7.916807,244.0,T8200 Processor,1.0,8.0,128.0,1024.0

In [ ]:
##Convert Data Types

df['Price'] = df['Price'].astype('int')
df['Star_Rating'] = df['Star_Rating'].astype('float')
df['RAM_GB'] = df['RAM_GB'].astype('float')

In [ ]:
df.dtypes

Name                  object
Company               object
Price                  int64
Star_Rating          float64
Number_of_Ratings    float64
Number_of_Reviews    float64
Processor             object
Warranty             float64
RAM_GB               float64
ROM_GB               float64
Expandable_GB        float64
dtype: object

In [ ]:
##Feature transformations (date parts, derived fields if required for analysis

df['Colour'] = df['Name'].str.split().str[3:-2]
df

,Name,Company,Price,Star_Rating,Number_of_Ratings,Number_of_Reviews,Processor,Warranty,RAM_GB,ROM_GB,Expandable_GB,Colour
0,"Google Pixel 10 Pro Fold (Moonstone, 256 GB)",Google,172999,4.3,8.262817,279.0,Tensor G5 Processor,1.0,16.0,256.0,2048.0,"[Pro, Fold, (Moonstone,]"
1,"Samsung Galaxy F36 5G (Red, 128 GB)",Samsung,15999,4.3,8.926252,439.0,Samsung Exynos 1380 Processor,1.0,6.0,128.0,2048.0,"[5G, (Red,]"
2,"POCO C71 (Cool Blue, 128 GB)",POCO,6799,4.1,10.122824,1190.0,Unisoc T7250\nMax clock speed: \n2 x A75@1.8GH...,1.0,6.0,128.0,2048.0,"[Blue,]"
3,"POCO M7 5G (Mint Green, 128 GB)",POCO,9999,4.2,9.448175,624.0,4 Gen 2 5G Processor,1.0,8.0,128.0,1024.0,"[(Mint, Green,]"
4,"Samsung Galaxy F36 5G (Black, 256 GB)",Samsung,19499,4.2,8.230311,267.0,Samsung Exynos 1380 Processor,1.0,8.0,256.0,2048.0,"[5G, (Black,]"
...,...,...,...,...,...,...,...,...,...,...,...,...
975,"Tecno Spark Go 1 (Startrail Black, 64 GB)",Tecno,6899,4.3,7.453562,82.0,Unisoc T61 Processor,1.0,3.0,64.0,1024.0,"[1, (Startrail, Black,]"
978,"OPPO F31 Pro+ 5G (Gemstone Blue, 256 GB)",OPPO,32999,4.4,5.236442,22.0,7 Gen 3 Mobile Platform Processor,1.0,8.0,256.0,2048.0,"[5G, (Gemstone, Blue,]"
979,"OPPO A5 5G (Mist White, 128 GB)",OPPO,15499,4.3,5.541264,9.0,Dimensity 6300 Processor,1.0,6.0,128.0,2048.0,"[(Mist, White,]"
982,GFive U550,GFive,899,3.7,5.068904,11.0,Samsung Exynos 1380 Processor,1.0,8.0,128.0,2048.0,[]
983,"Ai+ Nova 5G (Green, 128 GB)",Ai+,9999,3.8,7.916807,244.0,T8200 Processor,1.0,8.0,128.0,1024.0,"[(Green,]"

In [ ]:
def price_category(price):
    if price < 10000:
        return "Budget"
    elif price < 30000:
        return "Mid-Range"
    else:
        return "Premium"

df['Price_Category'] = df['Price'].apply(price_category)
df

,Name,Company,Price,Star_Rating,Number_of_Ratings,Number_of_Reviews,Processor,Warranty,RAM_GB,ROM_GB,Expandable_GB,Colour,Price_Category
0,"Google Pixel 10 Pro Fold (Moonstone, 256 GB)",Google,172999,4.3,8.262817,279.0,Tensor G5 Processor,1.0,16.0,256.0,2048.0,"[Pro, Fold, (Moonstone,]",Premium
1,"Samsung Galaxy F36 5G (Red, 128 GB)",Samsung,15999,4.3,8.926252,439.0,Samsung Exynos 1380 Processor,1.0,6.0,128.0,2048.0,"[5G, (Red,]",Mid-Range
2,"POCO C71 (Cool Blue, 128 GB)",POCO,6799,4.1,10.122824,1190.0,Unisoc T7250\nMax clock speed: \n2 x A75@1.8GH...,1.0,6.0,128.0,2048.0,"[Blue,]",Budget
3,"POCO M7 5G (Mint Green, 128 GB)",POCO,9999,4.2,9.448175,624.0,4 Gen 2 5G Processor,1.0,8.0,128.0,1024.0,"[(Mint, Green,]",Budget
4,"Samsung Galaxy F36 5G (Black, 256 GB)",Samsung,19499,4.2,8.230311,267.0,Samsung Exynos 1380 Processor,1.0,8.0,256.0,2048.0,"[5G, (Black,]",Mid-Range
...,...,...,...,...,...,...,...,...,...,...,...,...,...
975,"Tecno Spark Go 1 (Startrail Black, 64 GB)",Tecno,6899,4.3,7.453562,82.0,Unisoc T61 Processor,1.0,3.0,64.0,1024.0,"[1, (Startrail, Black,]",Budget
978,"OPPO F31 Pro+ 5G (Gemstone Blue, 256 GB)",OPPO,32999,4.4,5.236442,22.0,7 Gen 3 Mobile Platform Processor,1.0,8.0,256.0,2048.0,"[5G, (Gemstone, Blue,]",Premium
979,"OPPO A5 5G (Mist White, 128 GB)",OPPO,15499,4.3,5.541264,9.0,Dimensity 6300 Processor,1.0,6.0,128.0,2048.0,"[(Mist, White,]",Mid-Range
982,GFive U550,GFive,899,3.7,5.068904,11.0,Samsung Exynos 1380 Processor,1.0,8.0,128.0,2048.0,[],Budget
983,"Ai+ Nova 5G (Green, 128 GB)",Ai+,9999,3.8,7.916807,244.0,T8200 Processor,1.0,8.0,128.0,1024.0,"[(Green,]",Budget